"""add opening stock to products

Revision ID: 96bcc4d94126
Revises: e3828595ebda
Create Date: 2026-09-03 09:18:16.798714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96bcc4d94126'
down_revision = 'e3828595ebda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'opening_stock',
                sa.Numeric(precision=14, scale=3),
                nullable=False,
                server_default='0'
            )
        )

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('opening_stock')

    # ### end Alembic commands ###
